### ISSUE TITLE
[Possible bug] keyframes overwrite with multiple definitions

### ISSUE THREAD

**Issue by davesnx** [reasonml-labs/bs-css#140]
Hi!

I'm running into a problem while creating a library for animations on top of `bs-css`, since it doesn't work as it is in pure CSS.

Let me explain it better, inside a keyframe block you can easily add more than one definition of timing with different properties and doesn't get overwritten.

Example here: We have duplicity of timings with different properties to change, both are applied.
```css
@keyframes fancy {
  0% {
    opacity: 1;
  }

  0% {
    transform: translateY(1px);
  }

  50% {
    transform: translateY(20px);
  }

  100% {
    opacity: 0;
  }

  100% {
    transform: translateY(0px);
  }
}

#app {
  animation: fancy 1s ease;
  animation-iteration-count: infinite;
}
```
Here a codesandbox: https://codesandbox.io/embed/stupefied-gould-o206s

While in bs-css: 

```reason
 module Styles = {
  open Css;

  let bounce =
    keyframes([
      (0, [transform(scale(0.1, 0.1))]),
      (0, [opacity(0.0)]),
      (60, [transform(scale(1.2, 1.2))]),
      (60, [opacity(1.0)]),
      (100, [transform(scale(1.0, 1.0))]),
      (100, [opacity(1.0)]),
    ]);

  let root =
    style([
      width(px(50)),
      height(px(50)),
      backgroundColor(rgb(0, 0, 0)),
      animationName(bounce),
      animationDuration(2000),
      unsafe("animation-iteration-count", "infinite"),
    ]);
};

ReactDOMRe.renderToElementWithId(
  <div className=Styles.root> {ReasonReact.string("Hello!")} </div>,
  "index",
);
```
Here the codesandbox: https://codesandbox.io/embed/bs-css-possible-bug-ltjll
(Doesn't currently work on my computer, but I think you can create a small repro demo with that.)

The main problem is that `Css.keyframes` or emotion under the hood, overwrites the keyframe timing annotations.

I'm not aware if it's a big change of functionality or is it not. Since I'm creating a library that manages spring animations it would rely on the CSS spec where the keyframes work with duplicity.
