### ISSUE TITLE
animating different element on hover

### ISSUE THREAD

**Issue by idkjs** [reasonml-labs/bs-css#190]
How would I implement this `css`:

```css
li:hover ~ li p {
  animation: wave-animation 0.3s infinite;
}
```

Right now I have this:

![Screen Recording 2020-03-28 at 7 54 53 PM](https://user-images.githubusercontent.com/2370391/77836640-5105f280-712e-11ea-9768-73edb2680e9c.gif)

What Im trying to do is make the hand shake when i hover the words.

Thanks.
